.\"
.\" lprint-jobs man page for LPrint, a Label Printer Utility
.\"
.\" Copyright © 2019-2021 by Michael R Sweet.
.\"
.\" Licensed under Apache License v2.0.  See the file "LICENSE" for more
.\" information.
.\"
.TH lprint-jobs 1 "LPrint" "2021-12-21" "Michael R Sweet"
.SH NAME
lprint-jobs \- list pending print jobs.
.SH SYNOPSIS
.B lprint
.B jobs
[
.B \-d
.I PRINTER
] [
.B \-u
.I PRINTER-URI
]
.SH DESCRIPTION
This command lists pending print jobs.
If not specified, print jobs submitted to the default printer are listed.
.SH OPTIONS
The following options are recognized by
.B lprint jobs:
.TP 5
\fB\-d \fIPRINTER\fR
Specifies the printer queue to list.
.TP 5
\fB\-u \fIPRINTER-URI\fR
Specifies an "ipp:" or "ipps:" URI for a remote printer.
.SH SEE ALSO
.BR lprint (1),
.BR lprint-cancel (1),
.BR lprint-default (1).
.SH COPYRIGHT
Copyright \[co] 2019-2021 by Michael R Sweet.
