.\"
.\" lprint-drivers man page for LPrint, a Label Printer Utility
.\"
.\" Copyright © 2019-2020 by Michael R Sweet.
.\"
.\" Licensed under Apache License v2.0.  See the file "LICENSE" for more
.\" information.
.\"
.TH lprint-drivers 1 "LPrint" "January 4, 2020" "Michael R Sweet"
.SH NAME
lprint-drivers \- list drivers supported by the print server.
.SH SYNOPSIS
.B lprint
.B drivers
.SH DESCRIPTION
This command lists the supported printer drivers.
.SH SEE ALSO
.BR lprint (1),
.BR lprint-add (1),
.BR lprint-devices (1),
.BR lprint-modify (1).
.SH COPYRIGHT
Copyright \[co] 2019-2020 by Michael R Sweet.
