.\"
.\" lprint.conf man page for LPrint, a Label Printer Utility
.\"
.\" Copyright © 2019 by Michael R Sweet.
.\"
.\" Licensed under Apache License v2.0.  See the file "LICENSE" for more
.\" information.
.\"
.TH lprint.conf 5 "LPrint" "December 13, 2019" "Michael R Sweet"
.SH NAME
~/lprint.conf \- printer configuration file.
.SH DESCRIPTION
The
.B ~/.lprint.conf
file contains a list of the printer queues configured using the
.BR lprint-add (1),
.BR lprint-default (1),
.BR lprint-delete (1),
and
.BR lprint-modify (1)
commands.
.SH SEE ALSO
.BR lprint (1),
.BR lprint-add (1),
.BR lprint-default (1),
.BR lprint-delete (1),
.BR lprint-modify (1),
.BR lprint-server (1).
.SH COPYRIGHT
Copyright \[co] 2019 by Michael R Sweet.
