.\"
.\" lprint-default man page for LPrint, a Label Printer Utility
.\"
.\" Copyright © 2019-2021 by Michael R Sweet.
.\"
.\" Licensed under Apache License v2.0.  See the file "LICENSE" for more
.\" information.
.\"
.TH lprint-default 1 "LPrint" "2021-12-21" "Michael R Sweet"
.SH NAME
lprint-default \- set or get the default printer queue.
.SH SYNOPSIS
.B lprint
.B default
[
.B \-d
.I PRINTER
] [
.B \-u
.I PRINTER-URI
]
.SH DESCRIPTION
This command gets or sets the default printer queue.
When run without options, the current default printer is written to the standard output.
Otherwise, the default printer is changed.
.SH OPTIONS
The following options are recognized by
.B lprint default:
.TP 5
\fB\-d \fIPRINTER\fR
Specifies the new default printer queue.
.TP 5
\fB\-u \fIPRINTER-URI\fR
Specifies an "ipp:" or "ipps:" URI for a remote printer.
.SH SEE ALSO
.BR lprint (1),
.BR lprint-add (1),
.BR lprint-modify (1),
.BR lprint-printers (1).
.SH COPYRIGHT
Copyright \[co] 2019-2021 by Michael R Sweet.
