.\"
.\" lprint-shutdown man page for LPrint, a Label Printer Utility
.\"
.\" Copyright © 2019 by Michael R Sweet.
.\"
.\" Licensed under Apache License v2.0.  See the file "LICENSE" for more
.\" information.
.\"
.TH lprint-shutdown 1 "LPrint" "December 13, 2019" "Michael R Sweet"
.SH NAME
lprint-shutdown \- stop a running label print server.
.SH SYNOPSIS
.B lprint
.B shutdown
.SH DESCRIPTION
This command stops a running label print server.
.SH SEE ALSO
.BR lprint (1),
.BR lprint-server (1).
.SH COPYRIGHT
Copyright \[co] 2019 by Michael R Sweet.
