.\"
.\" lprint.conf man page for LPrint, a Label Printer Utility
.\"
.\" Copyright © 2019-2026 by Michael R Sweet.
.\"
.\" Licensed under Apache License v2.0.  See the file "LICENSE" for more
.\" information.
.\"
.TH lprint.conf 5 "LPrint" "2026-06-03" "Michael R Sweet"
.SH NAME
lprint.conf \- server configuration file.
.SH DESCRIPTION
The
.B lprint.conf
server configuration file provides default values for zero or more server
options.
LPrint will look in the
.BR /etc ,
.BR /usr/local/etc ,
.BR "/Library/Application Support" "(macOS) ,"
and/or
.B $SNAP_COMMON
directories for system-wide defaults and the
.BR $HOME/.config ,
.BR "$HOME/Library/Application Support" "(macOS) ,"
and/or
.B "%PROFILE%/AppData/Local"
(Windows) directories for per-user defaults.
.PP
Lines starting with the "#" character are comments, for example:
.nf
    # This is a comment
.fi
Otherwise, LPrint will look for options of the form "NAME=VALUE".
Multiple options can be specified on a line when separated by whitespace.
.SH EXAMPLES
Listen on the hostname "server.example.com" and log activity to the file "/var/log/lprint.log":
.nf
    # Listen on the server's published addresses...
    listen-hostname=server.example.com

    # Log file and level...
    log-file=/var/log/lprint.log log-level=debug
.fi
.SH SEE ALSO
.BR lprint-server (1).
.SH COPYRIGHT
Copyright \[co] 2019-2026 by Michael R Sweet.
