.\"
.\" lprint-devices man page for LPrint, a Label Printer Utility
.\"
.\" Copyright © 2019-2020 by Michael R Sweet.
.\"
.\" Licensed under Apache License v2.0.  See the file "LICENSE" for more
.\" information.
.\"
.TH lprint-devices 1 "LPrint" "January 4, 2020" "Michael R Sweet"
.SH NAME
lprint-devices \- list connected label printer devices.
.SH SYNOPSIS
.B lprint
.B devices
.SH DESCRIPTION
This command lists connected label printer devices.
.SH SEE ALSO
.BR lprint (1),
.BR lprint-add (1),
.BR lprint-drivers (1),
.BR lprint-modify (1).
.SH COPYRIGHT
Copyright \[co] 2019-2020 by Michael R Sweet.
