#!/bin/sh
#
# Script to start lprint as a server.
#
# Copyright © 2022 by Michael R Sweet
#
# Licensed under Apache License v2.0.  See the file "LICENSE" for more
# information.
#

exec lprint server -o log-file=- -o log-level=debug
