.\"
.\" ??? man page for LPrint, a Label Printer Utility
.\"
.\" Copyright © 2019 by Michael R Sweet.
.\"
.\" Licensed under Apache License v2.0.  See the file "LICENSE" for more
.\" information.
.\"
.TH lprint 1 "LPrint" "November 21, 2019" "Michael R Sweet"
.SH NAME
lprint \- description

.SH SYNOPSIS
.B lprint
.B foo
[
.B \-\-option
.I value
]

.SH DESCRIPTION
.B lprint
description of what this does.

.SH OPTIONS
The following options are recognized by
.B lprint:
.TP 5
\fB\-\-option \fIvalue\fR
Description of option.

.SH EXIT STATUS
The
.B lprint
program returns 1 if it is unable to ...

.SH ENVIRONMENT

.SH EXAMPLES

.SH SEE ALSO

.SH COPYRIGHT
Copyright \[co] 2019 by Michael R Sweet.
