#!/bin/sh
#
# makesrcdist - make a source distribution of lprint.
#

if test $# != 1; then
	echo "Usage: ./makesrcdist version"
	exit 1
fi

version=$1

echo Creating tag for release...
git tag -m "Tag $version" v$version
git push origin v$version

echo Creating lprint-$version.tar.gz...
git archive --format tar --prefix=lprint-$version/ HEAD | gzip -v9 >lprint-$version.tar.gz
gpg --detach-sign lprint-$version.tar.gz

